
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Telegram Action
        # You may pin to the exact commit or the version.
        # uses: xinthink/action-telegram@20b3085f4d1aa43c08c29411536b8b48658fc169
        uses: xinthink/action-telegram@v1.1
        with:
          # The Telegram Bot token
          botToken: ${{ secrets.TELEGRAM_SECRET }}
          # The target to which the message will be sent, can be a Telegram Channel or Group
          chatId: ${{ secrets.TELEGRAM_TO }}
          # The current status of the job: job.status, defaults to 'success'
          jobStatus: "ok"
          
                
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d
        uses: docker/build-push-action@v6.12.0
        with:
          context: .
    
       
                
          
