name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.x]

    steps:
    - uses: actions/checkout@v3

    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}

          Repository: ${{ github.repository }}

          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Copy files via ssh key
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 94.198.217.80
        username: root
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "templates/index.html,model.h5,app.py,LSTM.py"
        target: /srv

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Check dependencies for vulnerabilities
      run: |
        pip-audit

    - name: Build Docker image
      run: |
        docker build -t lstm .

    - name: Check Dockerfile vulnerabilities with Trivy
      run: |
        curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb -o trivy.deb
        sudo dpkg -i trivy.deb
        trivy image lstm

#    - name: Run tests
#      run: |
#        python -m unittest discover
#
#